name: lint

on: push

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v2.3.0
        with:
          version: v1.64.4
  gomod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
        id: go
      - uses: actions/checkout@v4
      - run: go mod tidy -diff
