name: test

on: push

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
        id: go
      - uses: actions/checkout@v4
      - run: go test ./...
